package com.wyw.jiangsu.db.local;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wyw.jiangsu.db.CodeXD;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CODE_XD".
*/
public class CodeXDDao extends AbstractDao<CodeXD, Long> {

    public static final String TABLENAME = "CODE_XD";

    /**
     * Properties of entity CodeXD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ACode = new Property(1, String.class, "ACode", false, "ACODE");
        public final static Property CName = new Property(2, String.class, "cName", false, "C_NAME");
    }


    public CodeXDDao(DaoConfig config) {
        super(config);
    }
    
    public CodeXDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CODE_XD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"ACODE\" TEXT," + // 1: ACode
                "\"C_NAME\" TEXT);"); // 2: cName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CODE_XD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CodeXD entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String ACode = entity.getACode();
        if (ACode != null) {
            stmt.bindString(2, ACode);
        }
 
        String cName = entity.getCName();
        if (cName != null) {
            stmt.bindString(3, cName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CodeXD entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String ACode = entity.getACode();
        if (ACode != null) {
            stmt.bindString(2, ACode);
        }
 
        String cName = entity.getCName();
        if (cName != null) {
            stmt.bindString(3, cName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public CodeXD readEntity(Cursor cursor, int offset) {
        CodeXD entity = new CodeXD( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ACode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // cName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CodeXD entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setACode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CodeXD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CodeXD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CodeXD entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
